import React from "react";
import {
  FaLightbulb,
  FaUserTie,
  FaLeaf,
  FaHeartbeat,
  FaDumbbell,
  FaCarrot,
  FaSpa,
  FaBrain,
  FaBriefcase,
  FaPiggyBank,
  FaGamepad,
  FaHandsHelping,
  FaGraduationCap,
  FaCalendarCheck,
  FaArrowUp,
  FaHandshake,
  FaLaptopCode,
  FaPlane,
  FaTree,
  FaUsers,
  FaPalette,
  FaMusic,
} from "react-icons/fa";

interface CategoryConfig {
  [key: string]: { name: string; bgColor: string; textColor: string; icon: () => JSX.Element };
}

export const categoryConfig: CategoryConfig = {
  Creativity: {
    name: "Creativity",
    bgColor: "bg-yellow-400",
    textColor: "text-yellow-400",
    icon: () => React.createElement(FaLightbulb),
  },
  "Personal Development": {
    name: "Personal Development",
    bgColor: "bg-blue-500",
    textColor: "text-blue-500",
    icon: () => React.createElement(FaUserTie),
  },
  Wellness: {
    name: "Wellness",
    bgColor: "bg-teal-400",
    textColor: "text-teal-400",
    icon: () => React.createElement(FaLeaf),
  },
  Health: {
    name: "Health",
    bgColor: "bg-red-400",
    textColor: "text-red-400",
    icon: () => React.createElement(FaHeartbeat),
  },
  Fitness: {
    name: "Fitness",
    bgColor: "bg-green-500",
    textColor: "text-green-500",
    icon: () => React.createElement(FaDumbbell),
  },
  Nutrition: {
    name: "Nutrition",
    bgColor: "bg-orange-500",
    textColor: "text-orange-500",
    icon: () => React.createElement(FaCarrot),
  },
  Lifestyle: {
    name: "Lifestyle",
    bgColor: "bg-purple-400",
    textColor: "text-purple-400",
    icon: () => React.createElement(FaSpa),
  },
  Mindfulness: {
    name: "Mindfulness",
    bgColor: "bg-blue-300",
    textColor: "text-blue-300",
    icon: () => React.createElement(FaBrain),
  },
  Career: {
    name: "Career",
    bgColor: "bg-gray-700",
    textColor: "text-gray-700",
    icon: () => React.createElement(FaBriefcase),
  },
  Finance: {
    name: "Finance",
    bgColor: "bg-green-600",
    textColor: "text-green-600",
    icon: () => React.createElement(FaPiggyBank),
  },
  Hobbies: {
    name: "Hobbies",
    bgColor: "bg-indigo-400",
    textColor: "text-indigo-400",
    icon: () => React.createElement(FaGamepad),
  },
  Relationships: {
    name: "Relationships",
    bgColor: "bg-pink-400",
    textColor: "text-pink-400",
    icon: () => React.createElement(FaHandsHelping),
  },
  Education: {
    name: "Education",
    bgColor: "bg-blue-600",
    textColor: "text-blue-600",
    icon: () => React.createElement(FaGraduationCap),
  },
  Productivity: {
    name: "Productivity",
    bgColor: "bg-yellow-500",
    textColor: "text-yellow-500",
    icon: () => React.createElement(FaCalendarCheck),
  },
  "Self-Improvement": {
    name: "Self-Improvement",
    bgColor: "bg-green-400",
    textColor: "text-green-400",
    icon: () => React.createElement(FaArrowUp),
  },
  Social: {
    name: "Social",
    bgColor: "bg-orange-400",
    textColor: "text-orange-400",
    icon: () => React.createElement(FaHandshake),
  },
  Technology: {
    name: "Technology",
    bgColor: "bg-purple-600",
    textColor: "text-purple-600",
    icon: () => React.createElement(FaLaptopCode),
  },
  Travel: {
    name: "Travel",
    bgColor: "bg-blue-400",
    textColor: "text-blue-400",
    icon: () => React.createElement(FaPlane),
  },
  Environment: {
    name: "Environment",
    bgColor: "bg-green-300",
    textColor: "text-green-300",
    icon: () => React.createElement(FaTree),
  },
  Community: {
    name: "Community",
    bgColor: "bg-yellow-600",
    textColor: "text-yellow-600",
    icon: () => React.createElement(FaUsers),
  },
  Art: {
    name: "Art",
    bgColor: "bg-pink-500",
    textColor: "text-pink-500",
    icon: () => React.createElement(FaPalette),
  },
  Music: {
    name: "Music",
    bgColor: "bg-red-500",
    textColor: "text-red-500",
    icon: () => React.createElement(FaMusic),
  },
  Dance: {
    name: "Dance",
    bgColor: "bg-purple-500",
    textColor: "text-purple-500",
    icon: () => React.createElement(FaMusic),
  },
};
